name: Update Navasan Prices

on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"
    timezone: "Asia/Tehran"
  - cron: "0 15 * * *"
    timezone: "Asia/Tehran"
  - cron: "0 19 * * *"
    timezone: "Asia/Tehran"

permissions:
  contents: write

jobs:
  update-prices:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Get prices from Navasan
        env:
          NAVASAN_API_KEY: ${{ secrets.NAVASAN_API_KEY }}
        run: |
          python src/fetch_prices.py

      - name: Get gold fund prices from TSETMC
        run: |
          python src/fetch_gold_funds.py

      - name: Append gold fund history
        run: |
          python src/update_gold_funds_history.py

      - name: Save updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/latest.json data/history.csv data/gold_funds.csv data/gold_funds_history.csv

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update prices"
            git push
          fi
