name: Test TGJU Market Prices

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-tgju:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Get market prices from TGJU
        run: |
          python src/fetch_tgju.py

      - name: Save TGJU test data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/tgju_market_latest.csv data/tgju_market_latest.json data/tgju_market_history.csv

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Test TGJU market prices"
            git push
          fi
