name: Update TGJU Market Prices

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"
      timezone: "Asia/Tehran"
    - cron: "0 15 * * *"
      timezone: "Asia/Tehran"
    - cron: "0 19 * * *"
      timezone: "Asia/Tehran"

permissions:
  contents: write

jobs:
  update-tgju:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Get market prices from TGJU
        run: |
          python src/fetch_tgju.py

      - name: Build TGJU dashboard output
        run: |
          python src/build_tgju_dashboard.py

      - name: Save updated TGJU data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/tgju_market_latest.csv data/tgju_market_latest.json data/tgju_market_history.csv data/tgju_dashboard.csv

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update TGJU market prices"
            git push
          fi
